browserName = chrome
appURL = https://tutorialsninja.com/demo/

firstName = Maria Leonora
lastName = Theresa
telephoneNumber = 09123456789
validPassword = 12345

mismatchingConfirmPassword = abcde
existingEmail = amotoori1@gmail.com
invalidEmailOne = amotoori
invalidEmailTwo = amotoori@
invalidEmailThree = amotoori@gmail
invalidEmailFour = amotoori@gmail.
invalidTelephoneNumber = abcde

registerPageURL = https://tutorialsninja.com/demo/index.php?route=account/register
homePageURL = https://tutorialsninja.com/demo/index.php?route=common/home